spring.application.name=api-gateway
server.port=8093

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Routes Gateway (nouvelle syntaxe)
spring.cloud.gateway.server.webmvc.routes[0].id=ms-offres
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MS-OFFRES
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/offres/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-candidats
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MS-CANDIDATS
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/candidats/**

# Keycloak JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/JobBoardRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/JobBoardRealm/protocol/openid-connect/certs